### ISSUE TITLE
Unit test could not be loaded

### ISSUE THREAD

**Issue by HongyuHe** [microsoft/MetaOpt#2]
Hi,

I'm trying to run the unit tests by simply instantiating the test templates. For example, `MetaOptimize.Test/DemandPinningTestsGurobi.cs`:
```cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace MetaOptimize.Test
{
    using Gurobi;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    /// <summary>
    /// uses Gurobi to test demand pinning.
    /// </summary>
    [TestClass]
    public class DemandPinningTestsGurobi : DemandPinningTests<GRBVar, GRBModel>
    {
        /// <summary>
        /// Initialize the test class.
        /// </summary>
        [TestInitialize]
        public void Initialize()
        {
            this.CreateSolver = () => new SolverGurobi();
        }

        /// <summary>
        /// Tests demand pinning on a diamond topology using Gurobi.
        /// </summary>
        [TestMethod]
        internal void RunTestDiamondTopo()
        {
            TestDiamondTopo();
        }
    }
}
```

However, I couldn't run it due to the error: "Unit test 'RunTestDiamondTopo' could not be loaded." I might've missed something as I'm new to c#, but could anyone help me out please?

**Comment by HongyuHe** [comment]
Hi Pooria,
I think the problem relates to apple silicon. Do you know how we can build the project for osx-arm64? 

I changed the following properties, but the binary still seems to have incorrect format.
```xml
<Platforms>arm64</Platforms>
<PlatformTarget>AnyCPU</PlatformTarget>
<RuntimeIdentifier>osx-arm64</RuntimeIdentifier>
```
I'd appreciate any help or suggestions! @PooriaNamyar

**Comment by behnazak** [comment]
Hello, thanks for your comment, we have only tested MetaOpt on Windows and on Linux and have not yet tried it on MAC OS. I would recommend trying one of these instead.
